openapi: 3.0.0
info:
  title: Dainagon
  description: Server Side Api
  version: 1.0.0

paths:
  /question:
    get:
      summary: Get questions list
      responses:
        "200":
          description: Response JSON
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/QuestionHeader"
              example:
                - questionNumber: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                  title: Hello World
                - questionNumber: 2ca83d64-5532-3542-ff24-1d462a22dac4
                  title: Add

  /question/{questionNumber}:
    get:
      summary: Get Question
      parameters:
        - in: path
          name: questionNumber
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Response Json
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
              example:
                questionNumber: 2ca83d64-5532-3542-ff24-1d462a22dac4
                title: Add
                description: Let's add two values together
                TestCases:
                  inputs: ["1 1", "2 4", "3 2"]
                  answers: ["2", "6", "5"]
                  errorMessages: ["Wrong value", "Wrong value", "Wrong value"]
                SyntaxAnalyses:
                  - title: Does it contain a return statement?
                    syntax: Write the syntax here
                  - title: Is the plus operator included?
                    sysntax: Write the syntax here

  /answer:
    post:
      summary: Post user's answer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAnswer"
      responses:
        "201":
          description: Created

components:
  schemas:
    QuestionHeader:
      type: object
      properties:
        questionNumber:
          type: string
          format: uuid
        title:
          type: string
      required:
        - questionNumber
        - title

    Question:
      type: object
      properties:
        questionNumber:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        TestCases:
          type: array
          items:
            $ref: "#/components/schemas/TestCase"
        SyntaxAnalyses:
          type: array
          items:
            $ref: "#/components/schemas/SyntaxAnalysis"
      required:
        - questionNumber
        - title
        - description
        - TestCases
        - SyntaxAnalyses

    TestCase:
      type: object
      properties:
        inputs:
          type: array
          items:
            type: string
          minItems: 1
        answers:
          type: array
          items:
            type: string
          minItems: 1
        errorMessages:
          type: array
          items:
            type: string
          minItems: 1
      required:
        - inputs
        - answers
        - errorMessages

    SyntaxAnalysis:
      type: object
      properties:
        title:
          type: string
        syntax:
          type: string
      required:
        - title
        - syntax

    UserAnswer:
      type: object
      properties:
        userID:
          type: string
          format: uuid
        questionNumber:
          type: string
          format: uuid
        isCorrect:
          type: boolean
      required:
        - userID
        - questionNumber
        - isCorrect
